language: haskell
ghc: 7.8

before_install:
 - cabal install cabal-install
 - cabal sandbox init
 - cabal sandbox add-source regexps-syntax
 
install: 
 - cabal --version
 - cabal install --only-dependencies

script: 
 - cabal test 
 - cd test/test_compiled && make
